use std::sync::Arc;

use crate::signals::{mean, std_dev};

use super::CorrelationData;

// ── ANSI colours (same palette as report/cli.rs) ──────────────────────────────

const RESET:  &str = "\x1b[0m";
const BOLD:   &str = "\x1b[1m";
const DIM:    &str = "\x1b[2m";
const GREEN:  &str = "\x1b[32m";
const RED:    &str = "\x1b[31m";
const YELLOW: &str = "\x1b[33m";
const CYAN:   &str = "\x1b[36m";
const WHITE:  &str = "\x1b[97m";

// ── Entry point ───────────────────────────────────────────────────────────────

pub fn print_correlation_report(corr_data: &Arc<CorrelationData>) {
    println!();
    println!("{BOLD}{WHITE}╔══════════════════════════════════════════════════════════════════╗{RESET}");
    println!("{BOLD}{WHITE}║           INDUSTRY CORRELATION REPORT                            ║{RESET}");
    println!("{BOLD}{WHITE}╚══════════════════════════════════════════════════════════════════╝{RESET}");
    println!();
    println!(
        "{BOLD}As of        {RESET}{}    {BOLD}Window   {RESET}90 days    {BOLD}Pairs   {RESET}{}",
        corr_data.as_of,
        corr_data.matrix.len()
    );
    println!("{DIM}────────────────────────────────────────────────────────────────────{RESET}");

    print_top_correlated(corr_data);
    print_least_correlated(corr_data);
    print_divergence_opportunities(corr_data);
    print_ascii_heatmap(corr_data);

    println!();
    println!("{DIM}Generated by portfolio-sim  •  not financial advice{RESET}");
    println!();
}

// ── Sections ──────────────────────────────────────────────────────────────────

fn print_top_correlated(corr_data: &Arc<CorrelationData>) {
    println!();
    println!("{BOLD}{CYAN}  MOST CORRELATED INDUSTRY PAIRS  (top 15){RESET}");
    println!();
    println!(
        "  {BOLD}{:<42}  {:<42}  {:>6}{RESET}",
        "Industry A", "Industry B", "r"
    );
    println!("  {DIM}{}{RESET}", "─".repeat(96));

    let sorted = corr_data.sorted_pairs();
    for (pair, r) in sorted.iter().take(15) {
        let col = corr_colour(*r);
        println!(
            "  {:<42}  {:<42}  {col}{:>+.3}{RESET}",
            truncate(&pair.0, 42),
            truncate(&pair.1, 42),
            r
        );
    }

    println!();
    println!("{DIM}────────────────────────────────────────────────────────────────────{RESET}");
}

fn print_least_correlated(corr_data: &Arc<CorrelationData>) {
    println!();
    println!("{BOLD}{CYAN}  LEAST CORRELATED INDUSTRY PAIRS  (bottom 10){RESET}");
    println!();
    println!(
        "  {BOLD}{:<42}  {:<42}  {:>6}{RESET}",
        "Industry A", "Industry B", "r"
    );
    println!("  {DIM}{}{RESET}", "─".repeat(96));

    let mut sorted = corr_data.sorted_pairs();
    sorted.sort_by(|a, b| a.1.partial_cmp(&b.1).unwrap_or(std::cmp::Ordering::Equal));

    for (pair, r) in sorted.iter().take(10) {
        let col = corr_colour(*r);
        println!(
            "  {:<42}  {:<42}  {col}{:>+.3}{RESET}",
            truncate(&pair.0, 42),
            truncate(&pair.1, 42),
            r
        );
    }

    println!();
    println!("{DIM}────────────────────────────────────────────────────────────────────{RESET}");
}

fn print_divergence_opportunities(corr_data: &Arc<CorrelationData>) {
    println!();
    println!("{BOLD}{CYAN}  CURRENT DIVERGENCE OPPORTUNITIES  (|pairs score| > 0.5){RESET}");
    println!();

    const MIN_R: f64 = 0.6;
    const DIV_THRESHOLD: f64 = 0.5;

    let mut opps: Vec<(String, String, f64, f64)> = Vec::new(); // (ind_a, ind_b, r, spread_z)

    let sorted = corr_data.sorted_pairs();
    for (pair, r) in sorted.iter().filter(|(_, r)| *r >= MIN_R) {
        let a = &pair.0;
        let b = &pair.1;

        let score = divergence_score(corr_data, a, b);
        if score.abs() > DIV_THRESHOLD {
            opps.push((a.clone(), b.clone(), *r, score));
        }
    }

    if opps.is_empty() {
        println!("  {DIM}No significant divergences detected.{RESET}");
    } else {
        println!(
            "  {BOLD}{:<42}  {:<42}  {:>5}  {:>7}{RESET}",
            "Industry A", "Industry B", "r", "DivScore"
        );
        println!("  {DIM}{}{RESET}", "─".repeat(102));

        opps.sort_by(|a, b| b.3.abs().partial_cmp(&a.3.abs()).unwrap_or(std::cmp::Ordering::Equal));
        for (a, b, r, score) in &opps {
            let col = if *score > 0.0 { GREEN } else { RED };
            let arrow = if *score > 0.0 { "↑ A underperformed" } else { "↓ A outperformed" };
            println!(
                "  {:<42}  {:<42}  {:.3}  {col}{:>+.3}{RESET}  {DIM}{arrow}{RESET}",
                truncate(a, 42),
                truncate(b, 42),
                r,
                score
            );
        }
    }

    println!();
    println!("{DIM}────────────────────────────────────────────────────────────────────{RESET}");
}

/// Compute the same divergence z-score used by PairsSignal for industry pair (a, b).
/// Returns -(spread / (1.5 * std)) clamped to [-1, 1].
fn divergence_score(corr_data: &Arc<CorrelationData>, a: &str, b: &str) -> f64 {
    let Some(ret_a) = corr_data.industry_returns.get(a) else { return 0.0 };
    let Some(ret_b) = corr_data.industry_returns.get(b) else { return 0.0 };

    let mut dates: Vec<chrono::NaiveDate> = ret_a.keys().copied().collect();
    dates.sort_unstable();

    let spread_series: Vec<f64> = dates
        .iter()
        .filter_map(|d| {
            let va = ret_a.get(d)?;
            let vb = ret_b.get(d)?;
            if va.is_finite() && vb.is_finite() {
                Some(va - vb)
            } else {
                None
            }
        })
        .collect();

    if spread_series.len() < 20 {
        return 0.0;
    }

    let std = std_dev(&spread_series);
    if std < 1e-9 {
        return 0.0;
    }

    let recent = &spread_series[spread_series.len().saturating_sub(10)..];
    let recent_div = mean(recent);

    (-(recent_div / (1.5 * std))).clamp(-1.0, 1.0)
}

fn print_ascii_heatmap(corr_data: &Arc<CorrelationData>) {
    println!();
    println!("{BOLD}{CYAN}  CORRELATION HEATMAP  (top 10 industries by data coverage){RESET}");
    println!();

    // Pick up to 10 industries with the most return data points
    let mut industries: Vec<(&String, usize)> = corr_data
        .industry_returns
        .iter()
        .map(|(ind, dates)| (ind, dates.len()))
        .collect();
    industries.sort_by(|a, b| b.1.cmp(&a.1));
    industries.truncate(10);
    let industries: Vec<&String> = industries.into_iter().map(|(ind, _)| ind).collect();

    let n = industries.len();
    if n < 2 {
        println!("  {DIM}Not enough industry data to render heatmap.{RESET}");
        return;
    }

    // Header row — abbreviated industry names
    let abbrev: Vec<String> = industries.iter().map(|s| abbrev_industry(s)).collect();

    print!("  {BOLD}{:<28}{RESET}", "");
    for ab in &abbrev {
        print!("  {BOLD}{:<6}{RESET}", ab);
    }
    println!();
    println!("  {DIM}{}{RESET}", "─".repeat(28 + n * 8));

    for i in 0..n {
        print!("  {:<28}", truncate(industries[i], 28));
        for j in 0..n {
            if i == j {
                print!("  {DIM}  1.00{RESET}");
                continue;
            }
            let r = corr_data
                .get_correlation(industries[i], industries[j])
                .unwrap_or(f64::NAN);

            if r.is_nan() {
                print!("  {DIM}   N/A{RESET}");
            } else {
                let col = corr_colour(r);
                print!("  {col}{:>+5.2}{RESET}", r);
            }
        }
        println!();
    }

    println!();
    println!("  {DIM}Colour: {GREEN}positive{RESET}{DIM}  {RED}negative{RESET}{DIM}  {YELLOW}near-zero{RESET}");
    println!("{DIM}────────────────────────────────────────────────────────────────────{RESET}");
}

// ── Helpers ───────────────────────────────────────────────────────────────────

fn corr_colour(r: f64) -> &'static str {
    if r > 0.3 {
        GREEN
    } else if r < -0.1 {
        RED
    } else {
        YELLOW
    }
}

fn truncate(s: &str, max: usize) -> String {
    if s.len() <= max {
        s.to_string()
    } else {
        format!("{}…", &s[..max.saturating_sub(1)])
    }
}

fn abbrev_industry(name: &str) -> String {
    // Take first letter of each word, max 6 chars
    let ab: String = name
        .split_whitespace()
        .filter_map(|w| w.chars().next())
        .collect::<String>()
        .to_uppercase();
    ab[..ab.len().min(6)].to_string()
}
